### ISSUE TITLE
启动后，在监控->环境信息 看到文件权限有红色图标

### ISSUE THREAD

**Issue by simon-shi87** [tryzealot/zealot-docker#12]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/60641737/157430816-58b8f3a8-249b-4441-a347-bcad31979439.png">

zealot 版本 4.3.1
系统版本: Linux-x86_64
docker: 20.10.3
Docker-Compose: v2.3.2

请问这个要如何解决，尝试进入容器，在这些目录下可以手动创建文件

**Comment by icyleaf** [comment]
红色代表以上路径没有写入权限，可能会影响上传、解析应用功能不可用，请问你的 volumes 是怎么绑定的

**Comment by simon-shi87** [comment]
local 和 docker volume都试过了，都会有这样的提示， 我配置的是无SSL的，在LB上配置了SSL，和这个有关系吗？
```

# USE SSL: false
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:5-alpine
    command: redis-server
    volumes:
      - zealot-redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:12-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "80:80"

volumes:
  zealot-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/zealot-data/zealot/uploads
  zealot-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/zealot-data/zealot/backup
  zealot-redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/zealot-data/redis
  zealot-postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/zealot-data/postgres
```
